# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_clientV1.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import main

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(471, 357)
        self.login_box = QtWidgets.QDialogButtonBox(Dialog)
        self.login_box.setGeometry(QtCore.QRect(110, 310, 341, 32))
        self.login_box.setOrientation(QtCore.Qt.Horizontal)
        self.login_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.login_box.setObjectName("login_box")
        self.ID = QtWidgets.QTextBrowser(Dialog)
        self.ID.setGeometry(QtCore.QRect(20, 30, 131, 31))
        self.ID.setObjectName("ID")
        self.Password = QtWidgets.QTextBrowser(Dialog)
        self.Password.setGeometry(QtCore.QRect(20, 70, 131, 31))
        self.Password.setObjectName("Password")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 150, 241, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/capcha.png"))
        self.label.setObjectName("label")
        self.ID_input = QtWidgets.QLineEdit(Dialog)
        self.ID_input.setGeometry(QtCore.QRect(190, 30, 201, 31))
        self.ID_input.setObjectName("ID_input")
        self.Password_input = QtWidgets.QLineEdit(Dialog)
        self.Password_input.setGeometry(QtCore.QRect(190, 70, 201, 31))
        self.Password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_input.setObjectName("Password_input")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(270, 180, 181, 41))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        self.login_box.accepted.connect(Dialog.accept)
        self.login_box.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ID.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ID</p></body></html>"))
        self.Password.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Password</p></body></html>"))


if __name__ == "__main__":
    import sys
    main.sel_test()
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
